name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Build
        env:
          REACT_APP_API_BASE: ${{ secrets.REACT_APP_API_BASE }}
          REACT_APP_CHECKIN_BASE: ${{ secrets.REACT_APP_CHECKIN_BASE }}
        run: yarn build

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: './build'
          target: '/var/www/temp'

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: rm -r /var/www/app.checkomo.com && mv /var/www/temp/build /var/www/app.checkomo.com
